#!/bin/sh

# A script to toggle solarized from light to dark and from dark to light.
# It simply creates symlinks from the right colour files to files that Xresources, muttrc and zathurarc will source.
# Vim has its own toggle, which comes bundled with the solarized theme.

STATUS=`cat $HOME/Scripts/solarizedtoggle/solarizedstatus`

if [ "$STATUS" == "dark" ]
then
    ln -sf $HOME/Software/solarized/xresources-colors-solarized/Xresources-light $HOME/Scripts/solarizedtoggle/Xsolarized
#    ln -sf $HOME/Software/solarized/mutt-colors-solarized/mutt-colors-solarized-dark-16.muttrc $HOME/.mutt/colors.muttrc
    cp   $HOME/Scripts/solarizedtoggle/zathuralight $HOME/.config/zathura/zathurarc
    newstatus="light"
    newstatusforvim="dark"
else
    ln -sf $HOME/Software/solarized/xresources-colors-solarized/Xresources $HOME/Scripts/solarizedtoggle/Xsolarized
#    ln -sf $HOME/Software/solarized/mutt-colors-solarized/mutt-colors-solarized-dark-16.muttrc $HOME/.mutt/colors.muttrc
    cp   $HOME/Scripts/solarizedtoggle/zathuradark $HOME/.config/zathura/zathurarc
    newstatus="dark"
    newstatusforvim="light"
fi

echo $newstatus > $HOME/Scripts/solarizedtoggle/solarizedstatus
echo $newstatusforvim > $HOME/Scripts/solarizedtoggle/solarizedstatusforvim
xrdb -merge $HOME/.Xresources

